# Generated by Django 4.1 on 2024-05-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_movie_director_remove_movie_release_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
