# Generated by Django 4.1 on 2024-05-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_watched_movies_count_stats_movies_watched_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='average_rating',
            new_name='avg_rating',
        ),
    ]
